PROJECT_DIRECTORY_PATH = ""
COMPILER_PATH = "g++"

SOLUTION_PATH = ""
STUPID_PATH = ""
CHECKER_PATH = ""
GEN_PATH = ""

SOLUTION_COMPILER_FLAGS = ""

USE_CHECKER_INSTEAD_OF_STUPID = False
PRINT_PASSED_TESTS = True
